function [ info_text ] = mc_tools1(A)
%MC_TOOLS1 Read and process the array A 
%Version: 0.1
%
%   This functions takes as input the photon list array generated by 
%   mc_read.m function and process these level 1 data.
%
%   info = MC_TOOLS()
    info_text = 'Process X done.';

end

